name: bPermissions
version: 2.3.0a
author: codename_B
website: http://tetragaming.com/codename_B/
main: de.bananaco.bpermissions.imp.Permissions
load: startup
commands:
  permissions:
    aliases: [p, bp, perm]
    description: reloads the nodes
    usage: /<command> save|reload
  user:
    aliases: [u, usr]
    description: messes with users
    usage: /<command> (see documentation)
  group:
    aliases: [g, grp]
    description: messes with groups
    usage: /<command> (see documentation)
  world:
    aliases: [w, wrl]
    description: selects a world
    usage: /<command> world


