name: bPermissions
version: 2.7residencefix
author: codename_B
website: http://tetragaming.com/codename_B/
main: de.bananaco.bpermissions.imp.Permissions
commands:
  permissions:
    aliases: [p, bp, perm]
    description: reloads the nodes
    usage: /<command> save|reload
  user:
    aliases: [u, usr]
    description: messes with users
    usage: /<command> (see documentation)
  group:
    aliases: [g, grp]
    description: messes with groups
    usage: /<command> (see documentation)
  world:
    aliases: [w, wrl]
    description: selects a world
    usage: /<command> world
  promote:
    aliases: [p, pr]
    description: promote a player
    usage: /<command> player (track) (world)
  demote:
    aliases: [d, de]
    description: demote a player
    usage: /<command> player (track) (world)


