name: bPermissions
version: 2.1.4b
author: codename_B
website: http://tetragaming.com/codename_B/
main: de.bananaco.permissions.Permissions
load: startup
commands:
  permissions:
    aliases: [p, bp, perm]
    description: reloads the nodes
    usage: |
      Need help? Visit http://bpermissions.com
